import React from 'react';
import {Route, Redirect} from 'react-router-dom';

const UserDetailsPage = () => {
    return ( 
          <div class="content">
            <div class="post"> 
            <h2><a href="#">Account User Entity Details</a></h2>
            {/* <!-- <p class="a"><span class="date">December 10 2008</span></p> --> */}
                <div class="details">
                    <div class="text_wrapper">
                        <p>Long id - Primary key of entity. </p>
                        <p>String name - Name of user, min length size is 4 max 40. Cannot be null. </p>
                        <p>String lastname - Last Name of user, min length size is 4 max 40. Cannot be null. </p>
                        <p>String email - The string has to be a well-formed email address. Max length size is 40. </p>
                        <p>String password - Password of user account, min length 6 max 20. Cannot be null. </p>
                        <p>String username - Is unique value autogenerated. </p>
                        <p>String userUniqueId - User unique id autogenerated. </p>
                        <p>String emailVerificationToken - JWT token required to activate the account. Sent during registration on email. </p>
                        <p>String passwordResetToken - JWT token required to reset password. Generated after request. </p>
                        <p>Set roles - Type of user roles. </p>
                        <p>Boolean active - Status of user account activation. False not active, true is active. </p>
                    </div>
                </div>
            </div>
            </div>
     );
}
 
export default UserDetailsPage;